#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

# Hackerfleet Technology Demonstrator License
# ===========================================
# Copyright (C) 2011-2014 riot <riot@hackerfleet.org> and others.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import random
import time

dice = json.load(open("dice.json", "r"))

seasons = ("winter", "spring", "summer", "fall")
season = seasons[int(time.localtime()[1] / 4)]

print("A nice randomized %s recipe:" % season)

for key in sorted(dice['allof'].keys()):
    print(random.choice(dice['allof'][key]))


print(random.choice(dice['oneof'][season + 'veggies']))
